### ISSUE TITLE
Opening images as SCIFIOCellImg from OMERO fails 

### ISSUE THREAD

**Issue by gab1one** [imagej/imagej-omero#79] opened 2018-05-25 14:56 UTC
The download of images via the OMEROFormat fails, if the source image on the OMERO server is either so large that the heuristic chooses SCIFIOCellImg or SCIFIOCellImg is provided as the target Factory to the Image. I tested this with a huge 2d image from the IDR:
http://idr.openmicroscopy.org/webclient/?show=image-1920093

The SCIFIOCellImg is created correctly, but if you start iterating over the pixels, it will break at some point (for me after about 50k-100k steps.  I suspect this problem originates in the plane translation code:  https://github.com/imagej/imagej-omero/blob/master/src/main/java/net/imagej/omero/OMEROFormat.java#L636

The assumption that images on OMERO always have this layout seem to be wrong.

**Comment by ctrueden** [comment] 2018-05-25 15:08
@gab1one Are you using the new SCIFIO built on ImgLib2 v5 with imglib2-cache?

**Comment by ctrueden** [comment] 2018-05-25 15:09
Also @gab1one Please do not link to line numbers of things on a branch tip—the link will become wrong over time. Always press Y first to get a fixed hash.

**Comment by gab1one** [comment] 2018-05-28 06:45
@ctrueden Yes I am, and good tip, I will remember that.

**Comment by ctrueden** [comment] 2018-05-29 22:52
@gab1one I'm curious to know if you can still reproduce this problem with the latest version of imagej-omero master branch. @awalter17 and I fixed some problems, including a SCIFIO bug.

I'll try to reproduce as well with a 1GB sample image (85 time points, 33 focal planes, 768x512), by writing a script that simply iterates every pixel in the entire image.

**Comment by ctrueden** [comment] 2018-05-30 07:37
@gab1one I just pushed a rewrite of the ZCT logic for `OMEROFormat`. I cannot reproduce your report here with these changes. Let me know if it works for you.

**Comment by ctrueden** [comment] 2018-05-30 07:39
I imported the `dub` dataset from https://loci.wisc.edu/software/sample-data using the OMERO.insight importer. This is 768X x 512Y x 33Z x 85T. I opened it via ImageJ-OMERO and then ran the following Groovy script:
```groovy
#@ Dataset dataset
#@ StatusService ss

// Intended for use testing OMERO cell images -- e.g., dub sample

sum = 0
count = 0
ss.clearStatus()
for (sample in dataset) {
	sum += sample.getRealDouble()
	count++
	if (count % 1000000 == 0) ss.showStatus("Processed " + count/1000000 + "M pixels")
}
ss.clearStatus()
println("sum = " + sum + ", count = " + count + ", mean = " + (sum / count))
```
The script ran till completion and gave a believable (considering floating point math limitations) result. No exceptions were generated.

**Comment by ctrueden** [comment] 2018-05-30 11:32
@gab1one Closing as fixed; please reopen if you continue having issues.

**Closed by ctrueden** 2018-05-30 11:32 UTC
Labels: bug
